version: '3.1'

services:
  db:
    image: postgres:12.19-bookworm
    restart: always
    container_name: ivsm_ecommerce_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ivsm-ecommerce

  pgadmin:
    image: dpage/pgadmin4:8.6
    restart: always
    container_name: ivsm_ecommerce_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8081:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ivsm-ecommerce
    depends_on:
      - db

volumes:
  postgres_data:
    external: true
  pgadmin_data:
    external: true
    
networks:
  ivsm-ecommerce:
    external: true